apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eas-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eas-rb
subjects:
  - kind: ServiceAccount
    name: eas-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eas-role

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eas-sa

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}

